

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: udemySpringChadDardy
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:8086
    
management:
  tracing:
    sampling:
      probability: 1.0
      
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"